version: "3"

services:
  # Application
  production_minecraft_server:
    image: itzg/minecraft-server@sha256:6833928529acc1d0a3592fb10cde069948f6974d012c1eab2e4b09122913847d
    ports:
      - ${TCP_PORT}:25565
      - ${UDP_PORT}:19132/udp
      - ${MRTRICS_PORT}:9940
    environment:
      EULA: "TRUE"
      TYPE: paper
      VERSION: 1.19
      TZ: Asia/Tokyo
    env_file:
      - ./.env
      - ./docker.env
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro

  # Backup
  production_minecraft_backup:
    image: itzg/mc-backup@sha256:e4bc2d2db35fe15b6781590352cc02c37e9d66710ac10dfd2fb1ea43cf25dcc9
    depends_on:
      - production_minecraft_server
    environment:
      - RCON_HOST=production_minecraft_server
      - BACKUP_INTERVAL=23h
      - PRUNE_BACKUPS_DAYS=3d
      - TZ=Asia/Tokyo
    volumes:
      - ./data:/data:ro
      - ./mc-backups:/backups
      - /etc/timezone:/etc/timezone:ro
